### ISSUE TITLE
Crashes attaching to Go binary

### ISSUE THREAD

**Issue by rgl** [frida/frida-python#12] opened 2014-05-31 10:19 UTC
I was trying to attach to a Go binary with a command line of:

`frida-trace -i GetAddrInfoW -i gethostbyname MakeDnsRequest.exe`

But the go process crashed with:

```
Addresses: %v [95.85.24.227]
panic: invalid memory address or nil pointer dereference
fatal error: panic during malloc
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x41d3ca]

runtime stack:
runtime.panic(0x4c4980, 0x5caa8f)
        C:/Development/Go/src/pkg/runtime/panic.c:233 +0x2c
runtime: unexpected return pc for runtime.sigpanic called from 0x7ff89ae50681

goroutine 1 [syscall]:
runtime.cgocall(0x4232c0, 0x392a28)
        C:/Development/Go/src/pkg/runtime/cgocall.c:149 +0x120 fp=0x392a18
syscall.Syscall6(0x7ff8a5622bb0, 0x4, 0xc0840079a0, 0x0, 0xc08401ee10, ...)
        C:/Development/Go/src/pkg/runtime/syscall_windows.goc:77 +0x57 fp=0x392a60
syscall.GetAddrInfoW(0xc0840079a0, 0x0, 0xc08401ee10, 0xc0840000b0, 0x0, ...)
        C:/Development/Go/src/pkg/syscall/zsyscall_windows_amd64.go:1559 +0x99 fp=0x392ac8
net.newLookupIP(0x4eacd0, 0xc, 0x0, 0x0, 0x0, ...)
        C:/Development/Go/src/pkg/net/lookup_windows.go:114 +0x157 fp=0x392c18
net.func┬À029(0x5ce460, 0xc08401edb0, 0x4eacd0, 0xc)
        C:/Development/Go/src/pkg/net/lookup.go:41 +0x38 fp=0x392c68
net.(*singleflight).Do(0x5ce460, 0x4eacd0, 0xc, 0x392d00, 0x0, ...)
        C:/Development/Go/src/pkg/net/singleflight.go:45 +0x1e1 fp=0x392cb0
net.lookupIPMerge(0x4eacd0, 0xc, 0x0, 0x0, 0x0, ...)
        C:/Development/Go/src/pkg/net/lookup.go:42 +0xc3 fp=0x392d60
net.LookupIP(0x4eacd0, 0xc, 0x0, 0x0, 0x0, ...)
        C:/Development/Go/src/pkg/net/lookup.go:31 +0x66 fp=0x392da0
net.lookupHost(0x4eacd0, 0xc, 0x0, 0x0, 0x0, ...)
        C:/Development/Go/src/pkg/net/lookup_windows.go:54 +0x83 fp=0x392e40
net.LookupHost(0x4eacd0, 0xc, 0x0, 0x0, 0x0, ...)
        C:/Development/Go/src/pkg/net/lookup.go:25 +0x66 fp=0x392e80
main.main()
        c:/Users/rgl/MEOCloud/Projects/MakeHttpRequest/MakeDnsRequest.go:11 +0x3f fp=0x392f48
runtime.main()
        C:/Development/Go/src/pkg/runtime/proc.c:220 +0x132 fp=0x392fa0
runtime.goexit()
        C:/Development/Go/src/pkg/runtime/proc.c:1394 fp=0x392fa8
```

The go source is:

``` go
package main

import (
    "fmt"
    "net"
    "time"
)

func main() {
    for {
        addrs, err := net.LookupHost("ruilopes.com")
        if err != nil {
            fmt.Println("Oops: %v", err)
            return
        }

        fmt.Println("Addresses: %v", addrs)

        time.Sleep(5 * time.Second)
    }
}
```

The binary was build with:

`go build MakeDnsRequest.go`

**Comment by oleavr** [comment] 2017-01-18 23:53
Duplicate of frida/frida-core#84.

**Closed by oleavr** 2017-01-18 23:53 UTC
