### ISSUE TITLE
Process closes as soon Stalker is attached

### ISSUE THREAD

**Issue by chaudhryfaisal** [frida/frida-python#16] opened 2014-12-22 06:41 UTC
Running on Windows 7 x64, Python 3.4.2
I  did a build from latest code from git following the instructions on the site using Visual Studio 2013 Express Edition 

I tried few examples from http://www.frida.re/docs/functions/ and I only had success using "Calling Functions" script. 

my program 
```cpp
// ConsoleApplication1.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <windows.h>

void
f(int n)
{
	printf("Number: %d\n", n);
}

int _tmain(int argc, _TCHAR* argv[])
{

	int i = 0;

	printf("f() is at %p\n", f);

	while (1)
	{
		f(i++);
		Sleep(1000);
	}
}

 
```
when I run the following script
```python
import frida

process = frida.attach("ConsoleApplication1.exe")
print([x.name for x in process.enumerate_modules()])
script = process.session.create_script("""
Stalker.follow(Process.getCurrentThreadId(), {
  events: {
    call: true, // CALL instructions: yes please
    ret: false, // RET instructions: no thanks
    exec: false // all instructions: no thanks
  },
  onReceive: function onReceive(events) {
    // Called with `events` containing a binary blob which is one or more
    // GumEvent structs.  See `gumevent.h` for the format. This is obviously a
    // terrible API that is subject to change once a better trade-off between
    // ease-of-use and performance has been found.
  },
  onCallSummary: function onCallSummary(summary) {
    // Called with `summary` being a key-value mapping of call target to number
    // of calls, in the current time window. You would typically implement this
    // instead of `onReceive` for efficiency.
  }
});
""")
script.load()
```
I get 
```console
['ConsoleApplication1.exe', 'ntdll.dll', 'kernel32.dll', 'KERNELBASE.dll', 'MSVCR120.dll', 'frida-agent-32.dll', 'DNSAPI.dll', 'msvcrt.dll', 'WS2_32.dll', 'RPCRT4.dll', 'SspiCli.dll', 'CRYPTBASE.dll', 'sechost.dll', 'NSI.dll', 'ole32.dll', 'GDI32.dll', 'USER32.dll', 'ADVAPI32.dll', 'LPK.dll', 'USP10.dll', 'WINMM.dll', 'SHELL32.dll', 'SHLWAPI.dll', 'PSAPI.DLL', 'IMM32.DLL', 'MSCTF.dll', 'ntmarta.dll', 'WLDAP32.dll']
Traceback (most recent call last):
  File "D:/_ETC/Frida/frida-python-master/src/example.py", line 26, in <module>
    script.load()
SystemError: The connection is closed````

and my application terminates

**Comment by oleavr** [comment] 2015-01-06 13:01
This looks like a regression introduced by a recent Frida update. Does the same thing happen if you remove the `onReceive` callback?

**Comment by oleavr** [comment] 2015-04-27 00:10
This should now be fixed in the latest code in git. Thanks for reporting!

**Closed by oleavr** 2015-04-27 00:10 UTC
